branch-defaults:
  prod:
    environment: parseserver
global:
  application_name: ParseServer
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
